# ppo_train_prompts.py

# Diverse training prompts for robust PPO training (210 prompts total)
training_prompts = [
    # AI/ML Concepts (50 prompts)
    "Explain artificial intelligence in simple terms:",
    "What are the ethical concerns with AI?",
    "Describe how neural networks learn:",
    "What is the difference between AI and ML?",
    "How does reinforcement learning work?",
    "What are transformers in deep learning?",
    "Explain the attention mechanism:",
    "What is supervised learning?",
    "Describe unsupervised learning:",
    "What is deep learning?",
    "How do GANs generate images?",
    "What is natural language processing?",
    "Explain computer vision applications:",
    "What is transfer learning?",
    "Describe the bias-variance tradeoff:",
    "How does backpropagation work?",
    "What are convolutional neural networks?",
    "Explain overfitting in machine learning:",
    "What are recommendation systems?",
    "Describe the future of AI:",
    "What is a loss function in ML?",
    "Explain gradient descent optimization:",
    "What are hyperparameters in ML?",
    "Describe model evaluation metrics:",
    "What is cross-validation?",
    "Explain regularization techniques:",
    "What is feature engineering?",
    "Describe dimensionality reduction:",
    "What is ensemble learning?",
    "Explain the curse of dimensionality:",
    "What is online learning?",
    "Describe reinforcement learning algorithms:",
    "What is Markov Decision Process?",
    "Explain Q-learning:",
    "What is policy gradient?",
    "Describe imitation learning:",
    "What is meta-learning?",
    "Explain few-shot learning:",
    "What is self-supervised learning?",
    "Describe contrastive learning:",
    "What is federated learning?",
    "Explain differential privacy in ML:",
    "What is explainable AI?",
    "Describe fairness in machine learning:",
    "What is algorithmic bias?",
    "Explain data augmentation:",
    "What is synthetic data generation?",
    "Describe ML model deployment:",
    "What is MLOps?",
    "Explain AI governance:",
    
    # Programming/Technical (30 prompts)
    "Explain object-oriented programming:",
    "What are design patterns?",
    "Describe version control systems:",
    "What is agile methodology?",
    "How do databases work?",
    "Explain REST APIs:",
    "What is microservices architecture?",
    "Describe containerization:",
    "What is DevOps?",
    "Explain cloud computing:",
    "How does encryption work?",
    "What are blockchain technologies?",
    "Describe cybersecurity best practices:",
    "What is quantum computing?",
    "Explain parallel processing:",
    "How do compilers work?",
    "What is memory management?",
    "Describe operating systems:",
    "What is network programming?",
    "Explain web development frameworks:",
    "How do mobile apps work?",
    "What is game development?",
    "Describe embedded systems:",
    "What is IoT?",
    "Explain robotics programming:",
    "How does computer graphics work?",
    "What is computer architecture?",
    "Describe algorithm complexity:",
    "What is data structures?",
    "Explain software testing:",
    
    # Science/Education (30 prompts)
    "Explain quantum mechanics basics:",
    "What is relativity theory?",
    "Describe the scientific method:",
    "How does evolution work?",
    "What is genetics?",
    "Explain cellular biology:",
    "Describe the human brain:",
    "What is climate change?",
    "Explain renewable energy:",
    "How do vaccines work?",
    "What is the immune system?",
    "Describe human anatomy:",
    "What is astronomy?",
    "Explain the solar system:",
    "How do black holes form?",
    "What is chemistry?",
    "Describe the periodic table:",
    "What is physics?",
    "Explain Newton's laws:",
    "How does electricity work?",
    "What is magnetism?",
    "Describe geology:",
    "What are tectonic plates?",
    "Explain weather patterns:",
    "How do ecosystems work?",
    "What is biodiversity?",
    "Describe environmental science:",
    "What is psychology?",
    "Explain cognitive science:",
    "How do we learn?",
    
    # Creative/Open-ended (30 prompts)
    "Write a short poem about technology:",
    "Create a story about a robot learning emotions:",
    "Describe a perfect future city:",
    "Imagine a conversation between AI and human:",
    "Write a dialogue about ethics in technology:",
    "Create a fictional technology invention:",
    "Describe how society might change with advanced AI:",
    "Write about the impact of automation on jobs:",
    "Imagine solving climate change with technology:",
    "Create a character who is an AI researcher:",
    "Write a letter to future generations about AI:",
    "Describe a day in life with personal AI assistants:",
    "Imagine discovering alien technology:",
    "Write about the ethics of AI in healthcare:",
    "Create a plot for a sci-fi movie about AI:",
    "Describe the ideal education system with AI:",
    "Write about privacy in the digital age:",
    "Imagine AI in art and creativity:",
    "Describe a world where humans and AI coexist:",
    "Write about the philosophical implications of AI:",
    "Create a futuristic transportation system:",
    "Describe AI in space exploration:",
    "Write about digital currencies and AI:",
    "Imagine AI solving world hunger:",
    "Describe sustainable technology solutions:",
    "Write about the role of AI in democracy:",
    "Create a scenario where AI prevents a disaster:",
    "Describe the future of work with AI:",
    "Write about human-AI collaboration:",
    "Imagine the next technological revolution:",
    
    # Practical/Instructional (30 prompts)
    "How to learn programming effectively:",
    "Steps to build a machine learning model:",
    "Guide to starting a tech career:",
    "How to debug code efficiently:",
    "Tips for effective team collaboration:",
    "Best practices for data analysis:",
    "How to give a technical presentation:",
    "Steps for scientific research:",
    "Guide to writing technical documentation:",
    "How to manage complex projects:",
    "Tips for effective problem solving:",
    "Best practices for code review:",
    "How to stay updated with technology:",
    "Steps to create a portfolio project:",
    "Guide to technical interviews:",
    "How to mentor junior developers:",
    "Tips for remote work productivity:",
    "Best practices for software design:",
    "How to handle technical debt:",
    "Steps for system architecture design:",
    "Guide to performance optimization:",
    "How to conduct user research:",
    "Tips for effective communication:",
    "Best practices for security:",
    "How to plan a product roadmap:",
    "Steps for quality assurance:",
    "Guide to open source contributions:",
    "How to balance innovation and stability:",
    "Tips for leadership in tech:",
    "Best practices for continuous learning:",
    
    # Philosophical/Ethical (20 prompts)
    "What is consciousness?",
    "Discuss free will vs determinism:",
    "What makes us human?",
    "Discuss the ethics of AI decision-making:",
    "What is the meaning of intelligence?",
    "Discuss the singularity hypothesis:",
    "What are human rights in digital age?",
    "Discuss automation and human purpose:",
    "What is ethical technology design?",
    "Discuss AI and moral responsibility:",
    "What is the future of privacy?",
    "Discuss bias in algorithmic systems:",
    "What is digital ethics?",
    "Discuss the social impact of AI:",
    "What is technological determinism?",
    "Discuss AI and creativity:",
    "What is the value of human labor?",
    "Discuss existential risks of AI:",
    "What is human dignity in AI era?",
    "Discuss the philosophy of technology:",
    
    # Current Events/Trends (20 prompts)
    "Discuss recent AI breakthroughs:",
    "What are current trends in ML?",
    "Discuss the impact of large language models:",
    "What is the state of AI regulation?",
    "Discuss AI in healthcare advancements:",
    "What are autonomous systems developments?",
    "Discuss AI in climate science:",
    "What are quantum computing advances?",
    "Discuss edge computing trends:",
    "What is the metaverse?",
    "Discuss Web3 and blockchain:",
    "What are digital twins?",
    "Discuss AI in education:",
    "What are smart city technologies?",
    "Discuss 5G/6G impact:",
    "What are sustainable tech innovations?",
    "Discuss space technology advances:",
    "What are biotechnology trends?",
    "Discuss digital health:",
    "What are future computing paradigms?",
]

# Separate set of evaluation prompts (not used during training)
evaluation_prompts = [
    # Technical Evaluation (different from training)
    "Explain how a CPU processes instructions:",
    "What is the difference between HTTP and HTTPS?",
    "Describe how a search engine ranks pages:",
    "How does machine translation work?",
    "What are the principles of good UI design?",
    "Explain how cryptocurrencies maintain security:",
    "Describe the process of software development:",
    "What is the role of an operating system kernel?",
    "How do compilers optimize code?",
    "Explain database normalization:",
    
    # Scientific Evaluation
    "Explain photosynthesis step by step:",
    "What causes earthquakes?",
    "How does the greenhouse effect work?",
    "Describe the water cycle in detail:",
    "What is DNA replication?",
    "Explain the theory of plate tectonics:",
    "How do vaccines stimulate immunity?",
    "What is the structure of an atom?",
    "Describe the human digestive system:",
    "Explain the process of mitosis:",
    
    # Creative/Scenario-based Evaluation
    "Write a short dialogue between two scientists debating AI ethics:",
    "Describe a world where renewable energy is 100% adopted:",
    "Imagine explaining the internet to someone from 1800s:",
    "Create a story about an AI discovering human emotions:",
    "Write a persuasive argument for space exploration:",
    "Describe how technology could solve world hunger:",
    "Imagine a conversation about privacy in 2050:",
    "Write about the challenges of interplanetary travel:",
    "Describe a day in a fully automated smart home:",
    "Create a futuristic medical breakthrough scenario:",
    
    # Philosophical/Complex Evaluation
    "Discuss the ethical implications of genetic engineering:",
    "What does it mean for an AI to be conscious?",
    "How should society regulate powerful AI systems?",
    "Discuss the balance between innovation and safety:",
    "What are the long-term societal impacts of automation?",
    "How do we define intelligence across different species?",
    "Discuss the role of technology in education reform:",
    "What ethical considerations exist for brain-computer interfaces?",
    "How can technology address climate change effectively?",
    "Discuss the future of human identity in digital age:",
]
